on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        name: "Publish core"
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./core/package.json"
      - uses: JS-DevTools/npm-publish@v1
        name: "Publish cli"
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./cli/package.json"